
package com.catl.integration.pi.ecn.erp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Ecndate_SendService", targetNamespace = "http://atlbattery.com/PLM/ECN_DATE", wsdlLocation = "http://cnpd020.catlbattery.com:50900/dir/wsdl?p=sa/8c5c10ea5cd932758c1eaee9b30f035c")
public class SIEcndateSendService
    extends Service
{

    private final static URL SIECNDATESENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIECNDATESENDSERVICE_EXCEPTION;
    private final static QName SIECNDATESENDSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ECN_DATE", "SI_Ecndate_SendService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.startList.address");
        System.out.println("SI_MSTAECreateOutService wsdl:" + wsdl);
    	
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIECNDATESENDSERVICE_WSDL_LOCATION = url;
        SIECNDATESENDSERVICE_EXCEPTION = e;
    }

    public SIEcndateSendService() {
        super(__getWsdlLocation(), SIECNDATESENDSERVICE_QNAME);
    }

    public SIEcndateSendService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIECNDATESENDSERVICE_QNAME, features);
    }

    public SIEcndateSendService(URL wsdlLocation) {
        super(wsdlLocation, SIECNDATESENDSERVICE_QNAME);
    }

    public SIEcndateSendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIECNDATESENDSERVICE_QNAME, features);
    }

    public SIEcndateSendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEcndateSendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIEcndateSend
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEcndateSend getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN_DATE", "HTTP_Port"), SIEcndateSend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEcndateSend
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEcndateSend getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN_DATE", "HTTP_Port"), SIEcndateSend.class, features);
    }

    /**
     * 
     * @return
     *     returns SIEcndateSend
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEcndateSend getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN_DATE", "HTTPS_Port"), SIEcndateSend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEcndateSend
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEcndateSend getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN_DATE", "HTTPS_Port"), SIEcndateSend.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIECNDATESENDSERVICE_EXCEPTION!= null) {
            throw SIECNDATESENDSERVICE_EXCEPTION;
        }
        return SIECNDATESENDSERVICE_WSDL_LOCATION;
    }

}
