
package com.catl.integration.pi.ecn.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Ecndate_Send", targetNamespace = "http://atlbattery.com/PLM/ECN_DATE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIEcndateSend {


    /**
     * 
     * @param mtEcndateRequest
     * @return
     *     returns com.catl.integration.pi.ecn.erp.DTEcndateResponse
     */
    @WebMethod(operationName = "SI_Ecndate_Send", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Ecndate_Response", targetNamespace = "http://atlbattery.com/PLM/ECN_DATE", partName = "MT_Ecndate_Response")
    public DTEcndateResponse siEcndateSend(
        @WebParam(name = "MT_Ecndate_Request", targetNamespace = "http://atlbattery.com/PLM/ECN_DATE", partName = "MT_Ecndate_Request")
        DTEcndateRequest mtEcndateRequest);

}
