
package com.catl.integration.trp.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITestSampleInfoWSService", targetNamespace = "http://service.in.ws.trp.catl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITestSampleInfoWSService {


    /**
     * 
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "self", targetNamespace = "http://service.in.ws.trp.catl.com/", className = "com.catl.integration.trp.client.Self")
    @ResponseWrapper(localName = "selfResponse", targetNamespace = "http://service.in.ws.trp.catl.com/", className = "com.catl.integration.trp.client.SelfResponse")
    public Object self();

    /**
     * 
     * @param testSampleInfo
     * @return
     *     returns com.catl.integration.trp.client.TestSampleInfoWSResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncTestSampleInfo", targetNamespace = "http://service.in.ws.trp.catl.com/", className = "com.catl.integration.trp.client.SyncTestSampleInfo")
    @ResponseWrapper(localName = "syncTestSampleInfoResponse", targetNamespace = "http://service.in.ws.trp.catl.com/", className = "com.catl.integration.trp.client.SyncTestSampleInfoResponse")
    public TestSampleInfoWSResponse syncTestSampleInfo(
        @WebParam(name = "testSampleInfo", targetNamespace = "")
        TestSampleInfoWSRequest testSampleInfo);

}
