
package com.catl.integration.trp.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.catl.common.util.PropertiesUtil;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITestSampleInfoWSServiceService", targetNamespace = "http://service.in.ws.trp.catl.com/", wsdlLocation = "http://172.26.38.89/ws/testSampleInfoWSService?wsdl")
public class ITestSampleInfoWSServiceService
    extends Service
{

    private final static URL ITESTSAMPLEINFOWSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ITESTSAMPLEINFOWSSERVICESERVICE_EXCEPTION;
    private final static QName ITESTSAMPLEINFOWSSERVICESERVICE_QNAME = new QName("http://service.in.ws.trp.catl.com/", "ITestSampleInfoWSServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PropertiesUtil.getValueByKey("config_trp_webserviceip"));
           // url = new URL("http://172.26.38.89/ws/testSampleInfoWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITESTSAMPLEINFOWSSERVICESERVICE_WSDL_LOCATION = url;
        ITESTSAMPLEINFOWSSERVICESERVICE_EXCEPTION = e;
    }

    public ITestSampleInfoWSServiceService() {
        super(__getWsdlLocation(), ITESTSAMPLEINFOWSSERVICESERVICE_QNAME);
    }

    public ITestSampleInfoWSServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITESTSAMPLEINFOWSSERVICESERVICE_QNAME, features);
    }

    public ITestSampleInfoWSServiceService(URL wsdlLocation) {
        super(wsdlLocation, ITESTSAMPLEINFOWSSERVICESERVICE_QNAME);
    }

    public ITestSampleInfoWSServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITESTSAMPLEINFOWSSERVICESERVICE_QNAME, features);
    }

    public ITestSampleInfoWSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITestSampleInfoWSServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITestSampleInfoWSService
     */
    @WebEndpoint(name = "ITestSampleInfoWSServicePort")
    public ITestSampleInfoWSService getITestSampleInfoWSServicePort() {
        return super.getPort(new QName("http://service.in.ws.trp.catl.com/", "ITestSampleInfoWSServicePort"), ITestSampleInfoWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITestSampleInfoWSService
     */
    @WebEndpoint(name = "ITestSampleInfoWSServicePort")
    public ITestSampleInfoWSService getITestSampleInfoWSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.in.ws.trp.catl.com/", "ITestSampleInfoWSServicePort"), ITestSampleInfoWSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITESTSAMPLEINFOWSSERVICESERVICE_EXCEPTION!= null) {
            throw ITESTSAMPLEINFOWSSERVICESERVICE_EXCEPTION;
        }
        return ITESTSAMPLEINFOWSSERVICESERVICE_WSDL_LOCATION;
    }

}
