
package com.catl.integration.pi.part.change;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_PN_CHANGECreateOutService", targetNamespace = "http://atlbattery.com/PLM/PN_CHANGE")
public class SIPNCHANGECreateOutService
    extends Service
{

    private final static URL SIPNCHANGECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIPNCHANGECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIPNCHANGECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/PN_CHANGE", "SI_PN_CHANGECreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.changePart.address");
        System.out.println("SIPNCHANGECreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPNCHANGECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIPNCHANGECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIPNCHANGECreateOutService() {
        super(__getWsdlLocation(), SIPNCHANGECREATEOUTSERVICE_QNAME);
    }

    public SIPNCHANGECreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPNCHANGECREATEOUTSERVICE_QNAME, features);
    }

    public SIPNCHANGECreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIPNCHANGECREATEOUTSERVICE_QNAME);
    }

    public SIPNCHANGECreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPNCHANGECREATEOUTSERVICE_QNAME, features);
    }

    public SIPNCHANGECreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIPNCHANGECreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIPNCHANGECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPNCHANGECreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/PN_CHANGE", "HTTP_Port"), SIPNCHANGECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPNCHANGECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPNCHANGECreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/PN_CHANGE", "HTTP_Port"), SIPNCHANGECreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIPNCHANGECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPNCHANGECreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/PN_CHANGE", "HTTPS_Port"), SIPNCHANGECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPNCHANGECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPNCHANGECreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/PN_CHANGE", "HTTPS_Port"), SIPNCHANGECreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPNCHANGECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIPNCHANGECREATEOUTSERVICE_EXCEPTION;
        }
        return SIPNCHANGECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
