
package com.catl.integration.pi.part.change;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_PN_CHANGECreateOut", targetNamespace = "http://atlbattery.com/PLM/PN_CHANGE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIPNCHANGECreateOut {


    /**
     * 
     * @param mtPNCHANGECreateRequest
     * @return
     *     returns com.catl.integration.pi.part.change.DTPNCHANGECreateResponse
     */
    @WebMethod(operationName = "SI_PN_CHANGECreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_PN_CHANGECreateResponse", targetNamespace = "http://atlbattery.com/PLM/PN_CHANGE", partName = "MT_PN_CHANGECreateResponse")
    public DTPNCHANGECreateResponse siPNCHANGECreateOut(
        @WebParam(name = "MT_PN_CHANGECreateRequest", targetNamespace = "http://atlbattery.com/PLM/PN_CHANGE", partName = "MT_PN_CHANGECreateRequest")
        DTPNCHANGECreateRequest mtPNCHANGECreateRequest);

}
