CREATE TABLE A_XML_OBJECTS
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_OBJECTS_PK PRIMARY KEY (ID) ENABLE
 )
 /
 CREATE TABLE A_XML_RELATEDOBJECTINFO
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CLASSNAME VARCHAR2(80 BYTE) NOT NULL ENABLE,
    IDA2A2 NUMBER NOT NULL ENABLE,
    IS_BRANCH NUMBER(1) NOT NULL ENABLE,   
  	SUBGROUP_ID    VARCHAR2(100),
  	SEED NUMBER(1) not NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_RELATEDOBJECTINFO_PK PRIMARY KEY (ID) ENABLE
 )
 /
 CREATE INDEX A_XML_RELATEDOBJECTINFO$IDX1 ON A_XML_RELATEDOBJECTINFO(CLASSNAME,IDA2A2) tablespace INDX
 /
  CREATE TABLE A_XML_LINKS
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    PARENT_TYPE     VARCHAR2(80 BYTE) NOT NULL ENABLE,
    PARENT_ID     NUMBER(14,0) NOT NULL ENABLE,
    PARENT_ROLE VARCHAR2(40) NOT NULL ENABLE,
    CHILD_TYPE     VARCHAR2(80) NOT NULL ENABLE,
    CHILD_ID     NUMBER(14,0) NOT NULL ENABLE,
    CHILD_ROLE VARCHAR2(40) NOT NULL ENABLE,    
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE, 
    CONSTRAINT A_XML_LINKS_PK PRIMARY KEY (ID) ENABLE
 )
/
CREATE UNIQUE INDEX A_XML_LINKS$indx1 ON A_XML_LINKS (parent_type, parent_id, parent_role, child_type, child_id, child_role)
/
CREATE TABLE A_XML_MENUCONFIG
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    USERREF     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_MENUCONFIG_PK PRIMARY KEY (ID) ENABLE
 )
 /
  CREATE TABLE A_XML_ROLEMEMBERSTEMPINFO 
   (	
    UNUMBER VARCHAR2(50) NOT NULL ENABLE, 
	ID NUMBER(14,0) NOT NULL ENABLE, 
	TYPE VARCHAR2(80) NOT NULL ENABLE, 
	CREATESTAMP DATE NOT NULL ENABLE, 
	UPDATESTAMP DATE NOT NULL ENABLE, 
	UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE, 
	CREATOR VARCHAR2(60) NOT NULL ENABLE, 
	UPDATEDBY VARCHAR2(60) NOT NULL ENABLE, 
	XML_CONTENT SYS.XMLTYPE , 
	 CONSTRAINT A_XML_ROLEMEMBERSTEMPINFO_PK PRIMARY KEY (ID) ENABLE
)
/
CREATE TABLE A_XML_RELATED_OBJECT_GROUP
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    PBO_CLASSNAME VARCHAR2(80 BYTE) NOT NULL ENABLE,
    PBO_ID   NUMBER(14,0) NOT NULL ENABLE,
    PBO_BRANCH_ID   NUMBER(14,0) NOT NULL ENABLE,
    PROCESS_ID   NUMBER(14,0) NOT NULL ENABLE,
    TEMPLATE_ID VARCHAR2(40 BYTE) NOT NULL ENABLE,
    GROUP_ID VARCHAR2(40 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_RELATED_OBJECT_GROUP_PK PRIMARY KEY (ID) ENABLE
 )
 /
 CREATE UNIQUE INDEX A_XML_RELATED_OBJECT_GROUP$1 ON A_XML_RELATED_OBJECT_GROUP (PROCESS_ID, GROUP_ID) TABLESPACE INDX
 /
 CREATE INDEX A_XML_RELATED_OBJECT_GROUP$2 ON A_XML_RELATED_OBJECT_GROUP (PBO_CLASSNAME, PBO_ID) TABLESPACE INDX
 /
 CREATE INDEX A_XML_RELATED_OBJECT_GROUP$3 ON A_XML_RELATED_OBJECT_GROUP (PBO_CLASSNAME, PBO_BRANCH_ID) TABLESPACE INDX
 /
 
 CREATE TABLE A_XML_RELATEDOBJECTMEMBER
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    PARENT_GROUP_ID   NUMBER(14,0) NOT NULL ENABLE,
    CLASSNAME VARCHAR2(80 BYTE) NOT NULL ENABLE,
    IDA2A2   NUMBER(14,0) NOT NULL ENABLE,
    SEED   NUMBER(1,0) NOT NULL ENABLE,
    BRANCH_ID NUMBER(14,0) NOT NULL ENABLE,
    SUBGROUP_ID VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_RELATEDOBJECTMEMBER_PK PRIMARY KEY (ID) ENABLE
 )
/
 
CREATE TABLE A_WS_TRANSCATION_LOGS
   (
    ID NUMBER(14,0) NOT NULL ENABLE, 
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,    
	WS_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	SERVICE_SIDE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CLIENT_SIDE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	CLIENT_ID VARCHAR2(20 BYTE), 
	SERVICE_CLASS VARCHAR2(100 BYTE), 
	SERVICE_METHOD VARCHAR2(100 BYTE), 
	CLIENT_CLASS VARCHAR2(100 BYTE), 
	CLIENT_METHOD VARCHAR2(100 BYTE), 
	START_TIME DATE, 
	FINISH_TIME DATE, 
	STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,	
	XML_CONTENT SYS.XMLTYPE, 
	 CONSTRAINT A_WS_TRANSCATION_LOGS_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE USERS  ENABLE
   )
/
CREATE TABLE A_XML_DESIGNDISABLEDOBJECTS
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    PBOID   NUMBER(14,0) NOT NULL ENABLE,
    PARTNUMBER     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    PARTNAME     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    PARTBRANCHID   NUMBER(14,0) NOT NULL ENABLE,
    REQUESTOR     VARCHAR2(60 BYTE),
    REASON     VARCHAR2(4000 BYTE),
    CHANGENO     VARCHAR2(32 BYTE),
    NEWPN     VARCHAR2(40 BYTE),
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_DESIGNDISABLEDOBJECTS_PK PRIMARY KEY (ID) ENABLE
 )
 /
 CREATE INDEX DESIGNDISABLEDOBJECTS$INDX1 on A_XML_DESIGNDISABLEDOBJECTS(PBOID) TABLESPACE INDX
 /
 
 CREATE TABLE A_XML_SOURCECHANGEOBJECTS
  (
    ID   NUMBER(14,0) NOT NULL ENABLE,
    TYPE VARCHAR2(80 BYTE) NOT NULL ENABLE,
    CREATESTAMP DATE NOT NULL ENABLE,
    UPDATESTAMP DATE NOT NULL ENABLE,
    UPDATECOUNT NUMBER(12,0) NOT NULL ENABLE,
    CREATOR     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    UPDATEDBY     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    PBOID   NUMBER(14,0) NOT NULL ENABLE,
    PARTNUMBER     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    PARTNAME     VARCHAR2(180 BYTE) NOT NULL ENABLE,
    PARTBRANCHID   NUMBER(14,0) NOT NULL ENABLE,
    PARTCREATOR     VARCHAR2(60 BYTE),
    PARTMODIFIER     VARCHAR2(60 BYTE),
    SOURCEBEFORE     VARCHAR2(60 BYTE),
    SOURCEAFTER     VARCHAR2(60 BYTE),
    CHANGEREASON     VARCHAR2(1000 BYTE),
    XML_CONTENT SYS.XMLTYPE ,
    CONSTRAINT A_XML_SOURCECHANGEOBJECTS PRIMARY KEY (ID) ENABLE
 )
 /
 CREATE INDEX SOURCECHANGEOBJECTS$INDX1 on A_XML_SOURCECHANGEOBJECTS(PBOID) TABLESPACE INDX
 /
 
 CREATE TABLE "A_TRANSACTION_AUDIT_RECORDS"
  (
    "ID"   NUMBER(14,0) NOT NULL ENABLE,
    "TYPE" VARCHAR2(80 BYTE) NOT NULL ENABLE,
    "SERVICE_TYPE"     VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "SERVICE_NAME"     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "PROVIDER_NAME"     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CONSUMER_NAME"     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CLIENT_ID"     VARCHAR2(40 BYTE) ,
    "CLIENT_IP_ADDR"     VARCHAR2(40 BYTE) ,
    "SERVICE_CLASS"     VARCHAR2(120 BYTE) NOT NULL ENABLE,
    "SERVICE_METHOD"     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "START_TIME"     DATE ,
    "FINISH_TIME"     DATE ,
    "STATUS"     VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CREATESTAMP" DATE NOT NULL ENABLE,
    "UPDATESTAMP" DATE NOT NULL ENABLE,
    "UPDATECOUNT" NUMBER(12,0) NOT NULL ENABLE,
    "CREATOR"     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "UPDATEDBY"     VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "XML_CONTENT" "SYS"."XMLTYPE" ,
    CONSTRAINT "A_TRANSACTION_AUDIT_RECORDS_PK" PRIMARY KEY ("ID") ENABLE
 )
 TABLESPACE "USERS" 
 /