
package com.catl.integration.pi.part.maturity;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZEIVRCreateOutService", targetNamespace = "http://atlbattery.com/PLM/ZEIVR")
public class SIZEIVRCreateOutService
    extends Service
{

    private final static URL SIZEIVRCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZEIVRCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIZEIVRCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ZEIVR", "SI_ZEIVRCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.updatePartMaturity.address");
        System.out.println("SI_ZEIVRCreateOutService wsdl:" + wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZEIVRCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIZEIVRCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIZEIVRCreateOutService() {
        super(__getWsdlLocation(), SIZEIVRCREATEOUTSERVICE_QNAME);
    }

    public SIZEIVRCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZEIVRCREATEOUTSERVICE_QNAME, features);
    }

    public SIZEIVRCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIZEIVRCREATEOUTSERVICE_QNAME);
    }

    public SIZEIVRCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZEIVRCREATEOUTSERVICE_QNAME, features);
    }

    public SIZEIVRCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZEIVRCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZEIVRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZEIVRCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZEIVR", "HTTP_Port"), SIZEIVRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZEIVRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZEIVRCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZEIVR", "HTTP_Port"), SIZEIVRCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZEIVRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZEIVRCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZEIVR", "HTTPS_Port"), SIZEIVRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZEIVRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZEIVRCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZEIVR", "HTTPS_Port"), SIZEIVRCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZEIVRCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIZEIVRCREATEOUTSERVICE_EXCEPTION;
        }
        return SIZEIVRCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
