
package com.catl.integration.pi.part.maturity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZEIVRCreateOut", targetNamespace = "http://atlbattery.com/PLM/ZEIVR")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZEIVRCreateOut {


    /**
     * 
     * @param mtZEIVRCreateRequest
     * @return
     *     returns com.catl.integration.pi.part.maturity.DTZEIVRCreateResponse
     */
    @WebMethod(operationName = "SI_ZEIVRCreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZEIVRCreateResponse", targetNamespace = "http://atlbattery.com/PLM/ZEIVR", partName = "MT_ZEIVRCreateResponse")
    public DTZEIVRCreateResponse siZEIVRCreateOut(
        @WebParam(name = "MT_ZEIVRCreateRequest", targetNamespace = "http://atlbattery.com/PLM/ZEIVR", partName = "MT_ZEIVRCreateRequest")
        DTZEIVRCreateRequest mtZEIVRCreateRequest);

}
