
package com.catl.integration.pi.bom.create;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_BOM_CreateCreateOut", targetNamespace = "http://atlbattery.com/PLM/Bom_create")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIBOMCreateCreateOut {


    /**
     * 
     * @param mtBOMCreateCreateRequest
     * @return
     *     returns com.catl.integration.pi.bom.create.DTBOMCreateCreateResponse
     */
    @WebMethod(operationName = "SI_BOM_CreateCreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_BOM_CreateCreateResponse", targetNamespace = "http://atlbattery.com/PLM/Bom_create", partName = "MT_BOM_CreateCreateResponse")
    public DTBOMCreateCreateResponse siBOMCreateCreateOut(
        @WebParam(name = "MT_BOM_CreateCreateRequest", targetNamespace = "http://atlbattery.com/PLM/Bom_create", partName = "MT_BOM_CreateCreateRequest")
        DTBomCreateCreateRequest mtBOMCreateCreateRequest);

}
