
package com.catl.integration.pi.bom.create;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_BOM_CreateCreateOutService", targetNamespace = "http://atlbattery.com/PLM/Bom_create")
public class SIBOMCreateCreateOutService
    extends Service
{

    private final static URL SIBOMCREATECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBOMCREATECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIBOMCREATECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/Bom_create", "SI_BOM_CreateCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.createBom.address");
        System.out.println("SIBOMCreateCreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBOMCREATECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIBOMCREATECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIBOMCreateCreateOutService() {
        super(__getWsdlLocation(), SIBOMCREATECREATEOUTSERVICE_QNAME);
    }

    public SIBOMCreateCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIBOMCREATECREATEOUTSERVICE_QNAME, features);
    }

    public SIBOMCreateCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIBOMCREATECREATEOUTSERVICE_QNAME);
    }

    public SIBOMCreateCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIBOMCREATECREATEOUTSERVICE_QNAME, features);
    }

    public SIBOMCreateCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBOMCreateCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIBOMCreateCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBOMCreateCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/Bom_create", "HTTP_Port"), SIBOMCreateCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBOMCreateCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBOMCreateCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/Bom_create", "HTTP_Port"), SIBOMCreateCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIBOMCreateCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBOMCreateCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/Bom_create", "HTTPS_Port"), SIBOMCreateCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBOMCreateCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBOMCreateCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/Bom_create", "HTTPS_Port"), SIBOMCreateCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBOMCREATECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIBOMCREATECREATEOUTSERVICE_EXCEPTION;
        }
        return SIBOMCREATECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
