
package com.catl.integration.pi.drawing;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZEINRCreateOutService", targetNamespace = "http://atlbattery.cpm/PLM/ZEINR")
public class SIZEINRCreateOutService
    extends Service
{

    private final static URL SIZEINRCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZEINRCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIZEINRCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.cpm/PLM/ZEINR", "SI_ZEINRCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.drawing.address");
        System.out.println("SIZEINRCreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZEINRCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIZEINRCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIZEINRCreateOutService() {
        super(__getWsdlLocation(), SIZEINRCREATEOUTSERVICE_QNAME);
    }

    public SIZEINRCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZEINRCREATEOUTSERVICE_QNAME, features);
    }

    public SIZEINRCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIZEINRCREATEOUTSERVICE_QNAME);
    }

    public SIZEINRCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZEINRCREATEOUTSERVICE_QNAME, features);
    }

    public SIZEINRCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZEINRCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZEINRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZEINRCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.cpm/PLM/ZEINR", "HTTP_Port"), SIZEINRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZEINRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZEINRCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.cpm/PLM/ZEINR", "HTTP_Port"), SIZEINRCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZEINRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZEINRCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.cpm/PLM/ZEINR", "HTTPS_Port"), SIZEINRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZEINRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZEINRCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.cpm/PLM/ZEINR", "HTTPS_Port"), SIZEINRCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZEINRCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIZEINRCREATEOUTSERVICE_EXCEPTION;
        }
        return SIZEINRCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
