
package com.catl.integration.pi.bom.change;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_BOM_CHANGECreateOutService", targetNamespace = "http://atlbattery.com/PLM/BOM_CHANGE")
public class SIBOMCHANGECreateOutService
    extends Service
{

    private final static URL SIBOMCHANGECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBOMCHANGECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIBOMCHANGECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/BOM_CHANGE", "SI_BOM_CHANGECreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.changeBom.address");
        System.out.println("SIBOMCHANGECreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBOMCHANGECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIBOMCHANGECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIBOMCHANGECreateOutService() {
        super(__getWsdlLocation(), SIBOMCHANGECREATEOUTSERVICE_QNAME);
    }

    public SIBOMCHANGECreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIBOMCHANGECREATEOUTSERVICE_QNAME, features);
    }

    public SIBOMCHANGECreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIBOMCHANGECREATEOUTSERVICE_QNAME);
    }

    public SIBOMCHANGECreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIBOMCHANGECREATEOUTSERVICE_QNAME, features);
    }

    public SIBOMCHANGECreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBOMCHANGECreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIBOMCHANGECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBOMCHANGECreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/BOM_CHANGE", "HTTP_Port"), SIBOMCHANGECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBOMCHANGECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBOMCHANGECreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/BOM_CHANGE", "HTTP_Port"), SIBOMCHANGECreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIBOMCHANGECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBOMCHANGECreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/BOM_CHANGE", "HTTPS_Port"), SIBOMCHANGECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBOMCHANGECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBOMCHANGECreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/BOM_CHANGE", "HTTPS_Port"), SIBOMCHANGECreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBOMCHANGECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIBOMCHANGECREATEOUTSERVICE_EXCEPTION;
        }
        return SIBOMCHANGECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
