
package com.catl.integration.pi.bom.change;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_BOM_CHANGECreateOut", targetNamespace = "http://atlbattery.com/PLM/BOM_CHANGE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIBOMCHANGECreateOut {


    /**
     * 
     * @param mtBOMCHANGECreateRequest
     * @return
     *     returns com.catl.integration.pi.bom.change.DTBOMCHANGECreateResponse
     */
    @WebMethod(operationName = "SI_BOM_CHANGECreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_BOM_CHANGECreateResponse", targetNamespace = "http://atlbattery.com/PLM/BOM_CHANGE", partName = "MT_BOM_CHANGECreateResponse")
    public DTBOMCHANGECreateResponse siBOMCHANGECreateOut(
        @WebParam(name = "MT_BOM_CHANGECreateRequest", targetNamespace = "http://atlbattery.com/PLM/BOM_CHANGE", partName = "MT_BOM_CHANGECreateRequest")
        DTBOMCHANGECreateRequest mtBOMCHANGECreateRequest);

}
