
package com.catl.integration.pi.part.disable;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_FAECreateOut", targetNamespace = "http://atlbattery.com/PLM/ZFAEP")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIFAECreateOut {


    /**
     * 
     * @param mtMATAECreateRequest
     * @return
     *     returns com.catl.integration.pi.part.disable.DTMSTAECreateResponse
     */
    @WebMethod(operationName = "SI_FAECreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_FAECreateResponse", targetNamespace = "http://atlbattery.com/PLM/ZFAEP", partName = "MT_FAECreateResponse")
    public DTFAECreateResponse siFAECreateOut(
        @WebParam(name = "MT_FAECreateRequest", targetNamespace = "http://atlbattery.com/PLM/ZFAEP", partName = "MT_FAECreateRequest")
        DTFAECreateRequest mtFAECreateRequest);

}
