
package com.catl.integration.pi.part.disable;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MSTAECreateOutService", targetNamespace = "http://atlbattery.com/PLM/MSTAE")
public class SIMSTAECreateOutService
    extends Service
{

    private final static URL SIMSTAECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMSTAECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIMSTAECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/MSTAE", "SI_MSTAECreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.disablePart.address");
        System.out.println("SI_MSTAECreateOutService wsdl:" + wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMSTAECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIMSTAECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIMSTAECreateOutService() {
        super(__getWsdlLocation(), SIMSTAECREATEOUTSERVICE_QNAME);
    }

    public SIMSTAECreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMSTAECREATEOUTSERVICE_QNAME, features);
    }

    public SIMSTAECreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMSTAECREATEOUTSERVICE_QNAME);
    }

    public SIMSTAECreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMSTAECREATEOUTSERVICE_QNAME, features);
    }

    public SIMSTAECreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMSTAECreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMSTAECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMSTAECreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/MSTAE", "HTTP_Port"), SIMSTAECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMSTAECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMSTAECreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/MSTAE", "HTTP_Port"), SIMSTAECreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMSTAECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMSTAECreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/MSTAE", "HTTPS_Port"), SIMSTAECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMSTAECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMSTAECreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/MSTAE", "HTTPS_Port"), SIMSTAECreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMSTAECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIMSTAECREATEOUTSERVICE_EXCEPTION;
        }
        return SIMSTAECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
