
package com.catl.integration.pi.part.disable;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MSTAECreateOut", targetNamespace = "http://atlbattery.com/PLM/MSTAE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMSTAECreateOut {


    /**
     * 
     * @param mtMATAECreateRequest
     * @return
     *     returns com.catl.integration.pi.part.disable.DTMSTAECreateResponse
     */
    @WebMethod(operationName = "SI_MSTAECreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_MSTAECreateResponse", targetNamespace = "http://atlbattery.com/PLM/MSTAE", partName = "MT_MSTAECreateResponse")
    public DTMSTAECreateResponse siMSTAECreateOut(
        @WebParam(name = "MT_MATAECreateRequest", targetNamespace = "http://atlbattery.com/PLM/MSTAE", partName = "MT_MATAECreateRequest")
        DTMSTAECreateRequest mtMATAECreateRequest);

}
