
package com.catl.integration.pi.file;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTZFILECreateOutService", targetNamespace = "http://atlbattery.com/PLM/ZTZFILE")
public class SIZTZFILECreateOutService
    extends Service
{

    private final static URL SIZTZFILECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTZFILECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIZTZFILECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ZTZFILE", "SI_ZTZFILECreateOutService");

    static {
        Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.file.address");
        System.out.println("SIZTZFILECreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        
        SIZTZFILECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIZTZFILECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIZTZFILECreateOutService() {
        super(__getWsdlLocation(), SIZTZFILECREATEOUTSERVICE_QNAME);
    }

    public SIZTZFILECreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTZFILECREATEOUTSERVICE_QNAME, features);
    }

    public SIZTZFILECreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIZTZFILECREATEOUTSERVICE_QNAME);
    }

    public SIZTZFILECreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTZFILECREATEOUTSERVICE_QNAME, features);
    }

    public SIZTZFILECreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTZFILECreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTZFILECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZTZFILECreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZTZFILE", "HTTP_Port"), SIZTZFILECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTZFILECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZTZFILECreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZTZFILE", "HTTP_Port"), SIZTZFILECreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZTZFILECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZTZFILECreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZTZFILE", "HTTPS_Port"), SIZTZFILECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTZFILECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZTZFILECreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZTZFILE", "HTTPS_Port"), SIZTZFILECreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTZFILECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIZTZFILECREATEOUTSERVICE_EXCEPTION;
        }
        return SIZTZFILECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
