
package com.catl.integration.pi.file;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTZFILECreateOut", targetNamespace = "http://atlbattery.com/PLM/ZTZFILE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTZFILECreateOut {


    /**
     * 
     * @param mtZTZFILECreateRequest
     * @return
     *     returns com.catl.integration.pi.file.DTZTZFILECreateResponse
     */
    @WebMethod(operationName = "SI_ZTZFILECreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTZFILECreateResponse", targetNamespace = "http://atlbattery.com/PLM/ZTZFILE", partName = "MT_ZTZFILECreateResponse")
    public DTZTZFILECreateResponse siZTZFILECreateOut(
        @WebParam(name = "MT_ZTZFILECreateRequest", targetNamespace = "http://atlbattery.com/PLM/ZTZFILE", partName = "MT_ZTZFILECreateRequest")
        DTZTZFILECreateRequest mtZTZFILECreateRequest);

}
