
package com.catl.integration.pi.ecn;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_EcnCreateOutService", targetNamespace = "http://atlbattery.com/PLM/ECN")
public class SIEcnCreateOutService
    extends Service
{

    private final static URL SIECNCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIECNCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIECNCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ECN", "SI_EcnCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.ecn.address");
        System.out.println("SIEcnCreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIECNCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIECNCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIEcnCreateOutService() {
        super(__getWsdlLocation(), SIECNCREATEOUTSERVICE_QNAME);
    }

    public SIEcnCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIECNCREATEOUTSERVICE_QNAME, features);
    }

    public SIEcnCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIECNCREATEOUTSERVICE_QNAME);
    }

    public SIEcnCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIECNCREATEOUTSERVICE_QNAME, features);
    }

    public SIEcnCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEcnCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIEcnCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEcnCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN", "HTTP_Port"), SIEcnCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEcnCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEcnCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN", "HTTP_Port"), SIEcnCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIEcnCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEcnCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN", "HTTPS_Port"), SIEcnCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEcnCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEcnCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ECN", "HTTPS_Port"), SIEcnCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIECNCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIECNCREATEOUTSERVICE_EXCEPTION;
        }
        return SIECNCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
