
package com.catl.integration.pi.ecn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_EcnCreateOut", targetNamespace = "http://atlbattery.com/PLM/ECN")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIEcnCreateOut {


    /**
     * 
     * @param mtEcnCreateRequest
     * @return
     *     returns com.catl.integration.pi.DTEcnCreateResponse
     */
    @WebMethod(operationName = "SI_EcnCreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_EcnCreateResponse", targetNamespace = "http://atlbattery.com/PLM/ECN", partName = "MT_EcnCreateResponse")
    public DTEcnCreateResponse siEcnCreateOut(
        @WebParam(name = "MT_EcnCreateRequest", targetNamespace = "http://atlbattery.com/PLM/ECN", partName = "MT_EcnCreateRequest")
        DTEcnCreateRequest mtEcnCreateRequest);

}
