
package com.catl.integration.pi.part.create;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MATNRCreateOutService", targetNamespace = "http://atlbattery.com/PLM/MATNR")
public class SIMATNRCreateOutService
    extends Service
{

    private final static URL SIMATNRCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMATNRCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIMATNRCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/MATNR", "SI_MATNRCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.createPart.address");
        System.out.println("SIMATNRCreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMATNRCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIMATNRCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIMATNRCreateOutService() {
        super(__getWsdlLocation(), SIMATNRCREATEOUTSERVICE_QNAME);
    }

    public SIMATNRCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMATNRCREATEOUTSERVICE_QNAME, features);
    }

    public SIMATNRCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMATNRCREATEOUTSERVICE_QNAME);
    }

    public SIMATNRCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMATNRCREATEOUTSERVICE_QNAME, features);
    }

    public SIMATNRCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMATNRCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMATNRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMATNRCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/MATNR", "HTTP_Port"), SIMATNRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMATNRCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMATNRCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/MATNR", "HTTP_Port"), SIMATNRCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMATNRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMATNRCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/MATNR", "HTTPS_Port"), SIMATNRCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMATNRCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMATNRCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/MATNR", "HTTPS_Port"), SIMATNRCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMATNRCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIMATNRCREATEOUTSERVICE_EXCEPTION;
        }
        return SIMATNRCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
