
package com.catl.integration.pi.part.sapfae;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZPLMNCreateOutService", targetNamespace = "http://atlbattery.com/PLM/ZPLMN")
public class SIZPLMNCreateOutService
    extends Service
{

    private final static URL SIZPLMNCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZPLMNCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIZPLMNCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ZPLMN", "SI_ZPLMNCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.startFaeProcess.address");
        System.out.println("SI_ZPLMNCreateOutService wsdl:" + wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZPLMNCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIZPLMNCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIZPLMNCreateOutService() {
        super(__getWsdlLocation(), SIZPLMNCREATEOUTSERVICE_QNAME);
    }

    public SIZPLMNCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZPLMNCREATEOUTSERVICE_QNAME, features);
    }

    public SIZPLMNCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIZPLMNCREATEOUTSERVICE_QNAME);
    }

    public SIZPLMNCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZPLMNCREATEOUTSERVICE_QNAME, features);
    }

    public SIZPLMNCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZPLMNCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZPLMNCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZPLMNCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZPLMN", "HTTP_Port"), SIZPLMNCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZPLMNCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZPLMNCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZPLMN", "HTTP_Port"), SIZPLMNCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZPLMNCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZPLMNCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZPLMN", "HTTPS_Port"), SIZPLMNCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZPLMNCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZPLMNCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZPLMN", "HTTPS_Port"), SIZPLMNCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZPLMNCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIZPLMNCREATEOUTSERVICE_EXCEPTION;
        }
        return SIZPLMNCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
