CREATE INDEX NFAEMaturityUp3DocPartLink$C0 ON NFAEMaturityUp3DocPartLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX NFAEMaturityUp3DocPartLink$C1 ON NFAEMaturityUp3DocPartLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
