
package com.catl.integration.pi.sourceChange;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_BESKZCreateOutService", targetNamespace = "http://atlbattery.com/PLM/BESKZ")
public class SIBESKZCreateOutService
    extends Service
{

    private final static URL SIBESKZCREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBESKZCREATEOUTSERVICE_EXCEPTION;
    private final static QName SIBESKZCREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/BESKZ", "SI_BESKZCreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.sourceChange.address");
        System.out.println("SIBESKZCreateOutService wsdl:"+wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBESKZCREATEOUTSERVICE_WSDL_LOCATION = url;
        SIBESKZCREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIBESKZCreateOutService() {
        super(__getWsdlLocation(), SIBESKZCREATEOUTSERVICE_QNAME);
    }

    public SIBESKZCreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIBESKZCREATEOUTSERVICE_QNAME, features);
    }

    public SIBESKZCreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIBESKZCREATEOUTSERVICE_QNAME);
    }

    public SIBESKZCreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIBESKZCREATEOUTSERVICE_QNAME, features);
    }

    public SIBESKZCreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBESKZCreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIBESKZCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBESKZCreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/BESKZ", "HTTP_Port"), SIBESKZCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBESKZCreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBESKZCreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/BESKZ", "HTTP_Port"), SIBESKZCreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIBESKZCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBESKZCreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/BESKZ", "HTTPS_Port"), SIBESKZCreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIBESKZCreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBESKZCreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/BESKZ", "HTTPS_Port"), SIBESKZCreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBESKZCREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIBESKZCREATEOUTSERVICE_EXCEPTION;
        }
        return SIBESKZCREATEOUTSERVICE_WSDL_LOCATION;
    }

}
