
package com.catl.integration.pi.sourceChange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_BESKZCreateOut", targetNamespace = "http://atlbattery.com/PLM/BESKZ")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIBESKZCreateOut {


    /**
     * 
     * @param mtBESKZCreateRequest
     * @return
     *     returns com.catl.integration.pi.sourceChange.DTBESKZCreateResponse
     */
    @WebMethod(operationName = "SI_BESKZCreateOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_BESKZCreateResponse", targetNamespace = "http://atlbattery.com/PLM/BESKZ", partName = "MT_BESKZCreateResponse")
    public DTBESKZCreateResponse siBESKZCreateOut(
        @WebParam(name = "MT_BESKZCreateRequest", targetNamespace = "http://atlbattery.com/PLM/BESKZ", partName = "MT_BESKZCreateRequest")
        DTBESKZCreateRequest mtBESKZCreateRequest);

}
