
package com.catl.integration.pi.part.fae;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import wt.services.applicationcontext.implementation.ServiceProperties;
import wt.util.WTException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZFAECreateOutService", targetNamespace = "http://atlbattery.com/PLM/ZFAE")
public class SIZFAECreateOutService
    extends Service
{

    private final static URL SIZFAECREATEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZFAECREATEOUTSERVICE_EXCEPTION;
    private final static QName SIZFAECREATEOUTSERVICE_QNAME = new QName("http://atlbattery.com/PLM/ZFAE", "SI_ZFAECreateOutService");

    static {
    	Properties props = null;
        try {
            props = ServiceProperties.getServiceProperties("WTServiceProviderFromProperties");
        } catch (WTException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        String wsdl = props.getProperty("sap.updatePartFae.address");
        System.out.println("SI_ZFAECreateOutService wsdl:" + wsdl);
        
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZFAECREATEOUTSERVICE_WSDL_LOCATION = url;
        SIZFAECREATEOUTSERVICE_EXCEPTION = e;
    }

    public SIZFAECreateOutService() {
        super(__getWsdlLocation(), SIZFAECREATEOUTSERVICE_QNAME);
    }

    public SIZFAECreateOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZFAECREATEOUTSERVICE_QNAME, features);
    }

    public SIZFAECreateOutService(URL wsdlLocation) {
        super(wsdlLocation, SIZFAECREATEOUTSERVICE_QNAME);
    }

    public SIZFAECreateOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZFAECREATEOUTSERVICE_QNAME, features);
    }

    public SIZFAECreateOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZFAECreateOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZFAECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZFAECreateOut getHTTPPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZFAE", "HTTP_Port"), SIZFAECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZFAECreateOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZFAECreateOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZFAE", "HTTP_Port"), SIZFAECreateOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZFAECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZFAECreateOut getHTTPSPort() {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZFAE", "HTTPS_Port"), SIZFAECreateOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZFAECreateOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZFAECreateOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://atlbattery.com/PLM/ZFAE", "HTTPS_Port"), SIZFAECreateOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZFAECREATEOUTSERVICE_EXCEPTION!= null) {
            throw SIZFAECREATEOUTSERVICE_EXCEPTION;
        }
        return SIZFAECREATEOUTSERVICE_WSDL_LOCATION;
    }

}
