CREATE INDEX ECAPartLink$COMPOSITE0 ON ECAPartLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ECAPartLink$COMPOSITE1 ON ECAPartLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
